# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Assistant' do
  pod 'AFNetworking'
  pod 'IQKeyboardManagerSwift'
  pod 'HandyJSON'
  pod 'MJRefresh'
  pod 'MBProgressHUD', '~>1.1.0'
end
